name: Llamar a tCloudDeploy cada 10 minutos

on:
  schedule:
    - cron: "*/10 * * * *"  # Ejecuta cada 10 minutos (UTC)
  workflow_dispatch:       # Permite ejecución manual

jobs:
  llamar-api:
    runs-on: ubuntu-latest
    steps:
      - name: Llamar a la API
        run: |
          echo "Llamando a la API..."
          curl -X GET https://smashnotes-springboot-back-1.onrender.com/apiSmash/tCloudDeploy
